name: FancyHolograms
description: $description
author: OliverHD
version: $version
folia-supported: true
main: de.oliver.fancyholograms.FancyHolograms
api-version: 1.19
load: POSTWORLD
softdepend:
  - FancyNpcs
  - PlaceholderAPI
  - MiniPlaceholders
commands:
  FancyHolograms:
    permission: FancyHolograms.admin
  Hologram:
    permission: FancyHolograms.admin
    description: Main command for the FancyHolograms plugin
    aliases:
      - holograms
      - holo