name: "FancyHolograms"
main: "de.oliver.fancyholograms.FancyHolograms"

version: "$version"
authors: [ "OliverHD", "Sxtanna" ]

description: "$description"

api-version: "1.19"
folia-supported: true

softdepend:
  - "FancyNpcs"
  - "PlaceholderAPI"
  - "MiniPlaceholders"
  - "ViaVersion"
  - "ViaBackwards"

commands:
  fancyholograms:
    permission: "fancyholograms.admin"
  hologram:
    permission: "fancyholograms.admin"
    description: "Main command for the FancyHolograms plugin"
    aliases:
      - "holograms"
      - "holo"
      - "fholo"